export const STRINGS = {
  en: {
    app_title: 'Palladium Secure Chat',
    login_title: 'Palladium Login',
    wif_label: 'WIF Private Key:',
    rpc_label: 'ElectrumX Connection',
    btn_rpc_settings: 'ElectrumX Settings',
    btn_start: 'Start & Scan',
    btn_gen_key: 'Create New Key',
    tab_chat: 'Chat',
    tab_profile: 'My Profile',
    tab_settings: 'Settings',
    contacts_title: 'CONTACTS',
    btn_new_contact: 'New Contact',
    btn_rescan: '⟳ Rescan Chain',
    lbl_select_contact: 'Select a Contact',
    btn_send: 'Send ➤',
    lbl_pk: 'My Public Key',
    lbl_addr: 'My Address',
    btn_reload_profile: 'Reload Data',
    setting_lang: 'Language:',
    setting_rescan: 'Rescan Time (Hours):',
    setting_retention: 'Delete history after (Days):',
    setting_fee_rate: 'Fee Rate (sat/vB):',
    setting_fee_rate_help: 'Transaction fee rate in satoshis per virtual byte. Lower = cheaper but slower. Recommended: 1-10. Minimum: 1.',
    setting_show_txid: 'Show full TXID in chat',
    setting_allow_unconfirmed: 'Use pending balance',
    btn_save_settings: 'Save Settings',
    msg_created: 'Key Created! Please save your WIF key securely!',
    msg_error: 'Error',
    msg_confirm_del: 'Really delete contact?',
    status_online: '● Online',
    status_sending: 'Sending...',
    status_sent: 'Sent: ',
    status_error: 'Error: ',
    dlg_new_name: 'Name:',
    dlg_new_key: 'Public Key (Hex):',
    dlg_rename: 'New Name:',
    no_coins: 'No coins on address!',
    warn_low_balance: '⚠️ Low Balance! Please top up PLM.',    warn_no_balance: '⛔ No PLM! Cannot send messages.',
    balance_label: 'Available Balance',
    balance_pending_label: 'Pending:',
    balance_total_label: 'Total:',
    balance_spendable_label: 'Spendable:',
    lbl_wif_show: 'Show Private Key (WIF)',
    btn_show: 'Show',
    btn_hide: 'Hide',
    btn_save: 'Save',
    btn_cancel: 'Cancel',
    btn_logout: 'Logout',
    msg_confirm_logout: 'Sign out and forget this account on this device?',
    lbl_rpc_host: 'ElectrumX Host',
    lbl_rpc_port: 'ElectrumX Port',
    lbl_rpc_user: 'Username',
    lbl_rpc_password: 'Password',
    amount_label: 'Amount (sat)',
    placeholder_message: 'Type your message...',
    setting_group_network: 'Network',
    setting_group_privacy: 'Privacy & History',
    setting_group_display: 'Display & UI',
    btn_force_rescan: 'Force Full Rescan',
    btn_clear_history: 'Clear Local History',
    btn_clear_cache: 'Clear Cache',
    setting_sound: 'Enable sound notifications',
    msg_confirm_clear_hist: 'Are you sure you want to delete ALL local message history? This cannot be undone.',
    msg_confirm_clear_cache: 'Clear local transaction cache? (App will reload)'
  },
  de: {
    app_title: 'Palladium Secure Chat',
    login_title: 'Palladium Anmeldung',
    wif_label: 'WIF Privater Schlüssel:',
    rpc_label: 'ElectrumX Verbindung',
    btn_rpc_settings: 'ElectrumX Einstellungen',
    btn_start: 'Starten & Scannen',
    btn_gen_key: 'Neuen Schlüssel erstellen',
    tab_chat: 'Chat',
    tab_profile: 'Mein Profil',
    tab_settings: 'Einstellungen',
    contacts_title: 'KONTAKTE',
    btn_new_contact: 'Neuer Kontakt',
    btn_rescan: '⟳ Blockchain Scannen',
    lbl_select_contact: 'Kontakt wählen',
    btn_send: 'Senden ➤',
    lbl_pk: 'Mein Public Key',
    lbl_addr: 'Meine Adresse',
    btn_reload_profile: 'Daten neu laden',
    setting_lang: 'Sprache:',
    setting_rescan: 'Rescan Zeit (Stunden):',
    setting_retention: 'Verlauf löschen nach (Tagen):',
    setting_fee_rate: 'Gebührensatz (sat/vB):',
    setting_fee_rate_help: 'Transaktionsgebühr in Satoshis pro virtuellem Byte. Niedriger = günstiger aber langsamer. Empfohlen: 1-10. Minimum: 1.',
    setting_show_txid: 'Volle TXID im Chat anzeigen',
    setting_allow_unconfirmed: 'Ausstehendes Guthaben nutzen',
    btn_save_settings: 'Einstellungen speichern',
    msg_created: 'Schlüssel erstellt! Bitte WIF sicher speichern!',
    msg_error: 'Fehler',
    msg_confirm_del: 'Kontakt wirklich löschen?',
    status_online: '● Online',
    status_sending: 'Sende...',
    status_sent: 'Gesendet: ',
    status_error: 'Fehler: ',
    dlg_new_name: 'Name:',
    dlg_new_key: 'Public Key (Hex):',
    dlg_rename: 'Neuer Name:',
    no_coins: 'Keine Coins auf der Adresse!',
    warn_low_balance: '⚠️ Wenig Guthaben! Bitte PLM aufladen.',    warn_no_balance: '⛔ Keine PLM! Senden nicht möglich.',
    balance_label: 'Verfügbares Guthaben',
    balance_pending_label: 'Ausstehend:',
    balance_total_label: 'Gesamt:',
    balance_spendable_label: 'Verfügbar:',
    lbl_wif_show: 'Privaten Schlüssel anzeigen (WIF)',
    btn_show: 'Anzeigen',
    btn_hide: 'Verbergen',
    btn_save: 'Speichern',
    btn_cancel: 'Abbrechen',
    btn_logout: 'Abmelden',
    msg_confirm_logout: 'Abmelden und dieses Konto auf diesem Gerät vergessen?',
    lbl_rpc_host: 'ElectrumX Host',
    lbl_rpc_port: 'ElectrumX Port',
    lbl_rpc_user: 'Benutzername',
    lbl_rpc_password: 'Passwort',
    amount_label: 'Betrag (sat)',
    placeholder_message: 'Nachricht eingeben...',
    setting_group_network: 'Netzwerk',
    setting_group_privacy: 'Privatsphäre & Verlauf',
    setting_group_display: 'Anzeige & UI',
    btn_force_rescan: 'Kompletter Rescan erzwingen',
    btn_clear_history: 'Lokalen Verlauf löschen',
    btn_clear_cache: 'Cache leeren',
    setting_sound: 'Sound-Benachrichtigungen aktivieren',
    msg_confirm_clear_hist: 'Bist du sicher, dass du den GESAMTEN lokalen Nachrichtenverlauf löschen willst? Das kann nicht rückgängig gemacht werden.',
    msg_confirm_clear_cache: 'Lokalen Transaktions-Cache leeren? (App wird neu geladen)'
  },
  ru: {
    app_title: 'Palladium Secure Chat',
    login_title: 'Вход в Palladium',
    wif_label: 'Приватный ключ (WIF):',
    rpc_label: 'Соединение ElectrumX',
    btn_rpc_settings: 'Настройки ElectrumX',
    btn_start: 'Запуск и Сканирование',
    btn_gen_key: 'Создать новый ключ',
    tab_chat: 'Чат',
    tab_profile: 'Мой профиль',
    tab_settings: 'Настройки',
    contacts_title: 'КОНТАКТЫ',
    btn_new_contact: 'Новый контакт',
    btn_rescan: '⟳ Сканировать сеть',
    lbl_select_contact: 'Выберите контакт',
    btn_send: 'Отправить ➤',
    lbl_pk: 'Мой Public Key',
    lbl_addr: 'Мой адрес',
    btn_reload_profile: 'Обновить данные',
    setting_lang: 'Язык:',
    setting_rescan: 'Время сканирования (часы):',
    setting_retention: 'Удалять историю через (дней):',
    setting_fee_rate: 'Ставка комиссии (sat/vB):',
    setting_fee_rate_help: 'Комиссия транзакции в сатоши за виртуальный байт. Ниже = дешевле но медленнее. Рекомендуется: 1-10. Минимум: 1.',
    setting_show_txid: 'Показывать полный TXID',
    setting_allow_unconfirmed: 'Использовать ожидающий баланс',
    btn_save_settings: 'Сохранить настройки',
    msg_created: 'Ключ создан! Сохраните WIF в надежном месте!',
    msg_error: 'Ошибка',
    msg_confirm_del: 'Удалить контакт?',
    status_online: '● В сети',
    status_sending: 'Отправка...',
    status_sent: 'Отправлено: ',
    status_error: 'Ошибка: ',
    dlg_new_name: 'Имя:',
    dlg_new_key: 'Public Key (Hex):',
    dlg_rename: 'Новое имя:',
    no_coins: 'Нет монет на адресе!',
    warn_low_balance: '⚠️ Мало средств! Пополните PLM.',    warn_no_balance: '⛔ Нет PLM! Отправка невозможна.',
    balance_label: 'Доступный баланс',
    balance_pending_label: 'Ожидает:',
    balance_total_label: 'Итого:',
    balance_spendable_label: 'Доступно:',
    lbl_wif_show: 'Показать приватный ключ (WIF)',
    btn_show: 'Показать',
    btn_hide: 'Скрыть',
    btn_save: 'Сохранить',
    btn_cancel: 'Отмена',
    btn_logout: 'Выйти',
    msg_confirm_logout: 'Выйти и забыть этот аккаунт на устройстве?',
    lbl_rpc_host: 'ElectrumX Хост',
    lbl_rpc_port: 'ElectrumX Порт',
    lbl_rpc_user: 'Имя пользователя',
    lbl_rpc_password: 'Пароль',
    amount_label: 'Сумма (sat)',
    placeholder_message: 'Введите сообщение...'
  },
  it: {
    app_title: 'Palladium Secure Chat',
    login_title: 'Accesso Palladium',
    wif_label: 'Chiave privata WIF:',
    rpc_label: 'Connessione ElectrumX',
    btn_rpc_settings: 'Impostazioni ElectrumX',
    btn_start: 'Avvia e Scansiona',
    btn_gen_key: 'Crea Nuova Chiave',
    tab_chat: 'Chat',
    tab_profile: 'Il Mio Profilo',
    tab_settings: 'Impostazioni',
    contacts_title: 'CONTATTI',
    btn_new_contact: 'Nuovo Contatto',
    btn_rescan: '⟳ Scansiona la Chain',
    lbl_select_contact: 'Seleziona un Contatto',
    btn_send: 'Invia ➤',
    lbl_pk: 'La Mia Public Key',
    lbl_addr: 'Il Mio Indirizzo',
    btn_reload_profile: 'Ricarica Dati',
    setting_lang: 'Lingua:',
    setting_rescan: 'Intervallo Rescan (Ore):',
    setting_retention: 'Cancella cronologia dopo (Giorni):',
    setting_fee_rate: 'Tariffa commissione (sat/vB):',
    setting_fee_rate_help: 'Tariffa commissione transazione in satoshi per byte virtuale. Più bassa = più economica ma più lenta. Consigliato: 1-10. Minimo: 1.',
    setting_show_txid: 'Mostra TXID completo in chat',
    setting_allow_unconfirmed: 'Usa saldo in pending',
    btn_save_settings: 'Salva Impostazioni',
    msg_created: 'Chiave creata! Salva il WIF in modo sicuro!',
    msg_error: 'Errore',
    msg_confirm_del: 'Vuoi davvero eliminare il contatto?',
    status_online: '● Online',
    status_sending: 'Invio...',
    status_sent: 'Inviato: ',
    status_error: 'Errore: ',
    dlg_new_name: 'Nome:',
    dlg_new_key: 'Public Key (Hex):',
    dlg_rename: 'Nuovo Nome:',
    no_coins: 'Nessuna moneta sull’indirizzo!',
    warn_low_balance: '⚠️ Saldo basso! Ricarica PLM.',    warn_no_balance: '⛔ Nessun PLM! Invio impossibile.',
    balance_label: 'Saldo disponibile',
    balance_pending_label: 'In attesa:',
    balance_total_label: 'Totale:',
    balance_spendable_label: 'Disponibile:',
    lbl_wif_show: 'Mostra chiave privata (WIF)',
    btn_show: 'Mostra',
    btn_hide: 'Nascondi',
    btn_save: 'Salva',
    btn_cancel: 'Annulla',
    btn_logout: 'Esci',
    msg_confirm_logout: 'Uscire e dimenticare questo account su questo dispositivo?',
    lbl_rpc_host: 'Host ElectrumX',
    lbl_rpc_port: 'Porta ElectrumX',
    lbl_rpc_user: 'Nome utente',
    lbl_rpc_password: 'Password',
    amount_label: 'Importo (sat)',
    placeholder_message: 'Scrivi il tuo messaggio...'
  }
};
